### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by GabMus** [nickgermaine/vinyl-music#1]
Hello there, first of all great work in bringing a material music player to Linux, well done.
This said it obviously needs lots of work, here are my thoughts on it. I don't really feel like opening a single issue for every single suggestion I'd want to leave you, so just allow me to write it all in one big issue.
1. Redundancy: player controls are both on the top right and on the middle bottom of the window. Decide where you prefer them and just get rid of one. Personally I think they make more sense in the bottom.
2. Redundancy 2: the overflow menu contains some entries that are the same to the left sidebar, remove the entries from the sidebar please.
3. Redundancy 3: there are like 3 ways to toggle shuffle mode, keep just the one in the bottom bar, and it's better if you color the icon when it's on, and make it gray when it's off, it's a lot better than having a label.
4. "Collection" tab on the toolbar: does this serve any purpose? Is this the hint of a soon-to-come feature?
5. Design: Add icons to the sidebar items, they'd look much better
6. Design 2: There's something wrong with the ripples in the music control buttons, try to figure it out and make the ripples circular and not touching the borders (I think the standard margin is something like 24px but I'm not sure)
7. Album Arts: why do you try to pull "AlbumArtSmall.jpg"? Just pull the album arts off the metadata. 

I'm not sure if you knew any of these issues, but you know, complaining is a way of contributing :P

**Comment by nickgermaine** [comment]
Thanks for the feedback.  In response, things are still very much undecided and out of place.  In the recent changed I've made, based on feedback of which controls to use (top or bottom), many people still like the traditional bottom controls, and so the top ones are removed now.

The left hand menu is still very undeveloped as right now albums/ allmuisc/ and artists are just file views, until I get the database imeplemented (next week).  Each of their views will change when that happens.

The shuffle control at the bottom will be the only one.

Collection means your local music files.  After that is all hammered out, I'll be exploring the option of integrating online services (like soundcloud, bandcamp, maybe even youtube at some point).

Icons: that's a great idea.  Again, its still very early, so a lot of these things will be looked at after the core fnctionality is implemented.

The album art: I'm working on (for the file view) selecting the first image file in the folder, regardless of the name/type.  Once the database is implemented, the album art will be scraped from each of the audios files.

Thanks for your feedback.  I am aware of all of this, and will be fixing when I get a chance.

Thanks for taking the time and having a look at it!
