### ISSUE TITLE
License

### ISSUE THREAD

**Issue by filcuc** [nickgermaine/vinyl-music#2]
You need to specify a license for this project

**Comment by nickgermaine** [comment]
Do I need to do this prior to a release?  Or just eventually?

**Comment by nickgermaine** [comment]
I've used the GPL2 license

**Comment by filcuc** [comment]
This a strong relation to contribution. It's not so easy to change a
license after you start having contributions. So think about it twice
before accepting pull requests. Otherwise you should make people sign a CLA.

2015-12-12 16:47 GMT+01:00 Nick notifications@github.com:

> Closed #2 https://github.com/nickgermaine/vinyl-music/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nickgermaine/vinyl-music/issues/2#event-490125214.

## 

Filippo Cucchetto
